"""initial schema

Revision ID: 2f7633b35633
Revises: 
Create Date: 2026-09-21 16:59:37.677056

Line-by-line verification against 0001_initial.sql:
- Autogenerated parts:
  - All 8 tables: job_failures, plans, webhook_events, tenants, idempotency_keys, subscriptions, usage_rollups, usage_events
  - Table columns, types, nullability, defaults (UUID gen_random_uuid, timestamps, jsonb defaults)
  - Foreign key constraints with ON DELETE CASCADE where specified
  - Check constraints: ck_plans_api_call_limit, ck_plans_token_limit, ck_usage_events_quantity, ck_usage_events_unit_price, ck_usage_events_cost, ck_category_matches_type
  - Unique constraints and composite unique constraint uq_idem_tenant_key
  - Indexes including partial unique index idx_sub_one_active_per_tenant with status WHERE clause
  - Descending composite indexes idx_usage_tenant_time, idx_usage_tenant_type_time
- Hand-patched parts:
  - Initial seed data insert for `plans` table ('free' and 'pro' plans from 0001_initial.sql)
  - Explicit PostgreSQL enum type cleanup on downgrade (plan_code, sub_status, idem_state, usage_type, token_category)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f7633b35633'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_failures',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.Enum('free', 'pro', name='plan_code'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('api_call_limit', sa.BigInteger(), nullable=False),
    sa.Column('token_limit', sa.BigInteger(), nullable=False),
    sa.Column('stripe_price_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('api_call_limit >= 0', name='ck_plans_api_call_limit'),
    sa.CheckConstraint('token_limit >= 0', name='ck_plans_token_limit'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('webhook_events',
    sa.Column('stripe_event_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('stripe_event_id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.SmallInteger(), nullable=False),
    sa.Column('api_key_hash', sa.Text(), nullable=False),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index('idx_tenants_stripe_customer', 'tenants', ['stripe_customer_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('in_progress', 'completed', name='idem_state'), server_default=sa.text("'in_progress'::idem_state"), nullable=False),
    sa.Column('response_status', sa.SmallInteger(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_idem_tenant_key')
    )
    op.create_index('idx_idem_created_at', 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.SmallInteger(), nullable=False),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'trialing', 'past_due', 'canceled', 'unpaid', 'incomplete', name='sub_status'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index('idx_sub_one_active_per_tenant', 'subscriptions', ['tenant_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'trialing', 'past_due')"))
    op.create_table('usage_rollups',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('api_calls_used', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('tokens_used', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_micro_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('by_category', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'period')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('api_call', 'tokens', name='usage_type'), nullable=False),
    sa.Column('category', sa.Enum('input', 'cached_input', 'output', 'reasoning', name='token_category'), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('unit_price_micro_cents', sa.BigInteger(), nullable=False),
    sa.Column('cost_micro_cents', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'api_call' AND category IS NULL) OR (type = 'tokens' AND category IS NOT NULL)", name='ck_category_matches_type'),
    sa.CheckConstraint('cost_micro_cents >= 0', name='ck_usage_events_cost'),
    sa.CheckConstraint('quantity > 0', name='ck_usage_events_quantity'),
    sa.CheckConstraint('unit_price_micro_cents >= 0', name='ck_usage_events_unit_price'),
    sa.ForeignKeyConstraint(['idempotency_id'], ['idempotency_keys.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_tenant_time', 'usage_events', ['tenant_id', sa.text('occurred_at DESC')], unique=False)
    op.create_index('idx_usage_tenant_type_time', 'usage_events', ['tenant_id', 'type', sa.text('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###

    # ### Hand-patched seed data from 0001_initial.sql ###
    plans_table = sa.table(
        'plans',
        sa.column('code', sa.Enum('free', 'pro', name='plan_code')),
        sa.column('display_name', sa.Text),
        sa.column('api_call_limit', sa.BigInteger),
        sa.column('token_limit', sa.BigInteger),
    )
    op.bulk_insert(
        plans_table,
        [
            {'code': 'free', 'display_name': 'Free', 'api_call_limit': 1000, 'token_limit': 100000},
            {'code': 'pro', 'display_name': 'Pro', 'api_call_limit': 50000, 'token_limit': 5000000},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usage_tenant_type_time', table_name='usage_events')
    op.drop_index('idx_usage_tenant_time', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('usage_rollups')
    op.drop_index('idx_sub_one_active_per_tenant', table_name='subscriptions', postgresql_where=sa.text("status IN ('active', 'trialing', 'past_due')"))
    op.drop_table('subscriptions')
    op.drop_index('idx_idem_created_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('idx_tenants_stripe_customer', table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('webhook_events')
    op.drop_table('plans')
    op.drop_table('job_failures')
    # ### end Alembic commands ###

    # ### Hand-patched enum type drops ###
    sa.Enum(name='idem_state').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='token_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='usage_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sub_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='plan_code').drop(op.get_bind(), checkfirst=True)
